# Generated by Django 4.0.1 on 2024-02-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0005_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
