# Generated by Django 4.0.1 on 2024-03-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0002_alter_comment_author_alter_comment_post'),
        ('core_user', '0008_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments_liked',
            field=models.ManyToManyField(related_name='commented_by', to='core_comment.Comment'),
        ),
    ]
